### ISSUE TITLE
view source buttons for "Circles and cubic Bézier curves" don't work

### ISSUE THREAD

**Issue by louisremi** [Pomax/bezierinfo#43] opened 2014-12-15 10:17 UTC

**Comment by Pomax** [comment] 2015-03-06 18:29
dupe of https://github.com/Pomax/bezierinfo/issues/46

**Closed by Pomax** 2015-03-06 18:29 UTC

**Comment by ocornut** [comment] 2015-08-27 21:40
Same here, tried Chrome and Firefox. Amazing site otherwise!
